### ISSUE TITLE
Slow down knockback?

### ISSUE THREAD

**Issue by TS440S** [LoneWolfHT/knockback#1]
First of all, I fully understand this is not a serious mod. But, is there any way to slow down the speed of the movement? It's unrealistically jerky. If not, no worries I still love this.

**Comment by LoneWolfHT** [comment]
Not really possibly without adding more moveto()s unfortunately. It looks fine to observers. Just not the player being hit

**Comment by TS440S** [comment]
Ok. Also. may I have permission to include this mod with a modpack I'm making? Full credit of course. I'm making a Better PvP engine modpack that has better swords, armour, health, and hopefully your knockback mod.

**Comment by LoneWolfHT** [comment]
Sure, it's MIT.
I've been working on some improvements recently. So you might have to update it a few times. Maybe watch the releases for this mod

**Comment by TS440S** [comment]
I am watching the releases. I've messed with the code a bit to tweak it to my liking(KB ammount) But the jerky upwards teleport for the person being hit is troubling me, I can't figure out how to make there be no upwards movement when hitting. I set the `pos.y = pos.y + 0.2` to 0.0 but that makes the player getting hit move down, not no movement. How can I disable the Y axis movement altogether?

**Comment by LoneWolfHT** [comment]
Set dir.y to 0
In the update the jump height should be less dramatic

**Comment by TS440S** [comment]
OK
Did you update the mod?

**Comment by LoneWolfHT** [comment]
Not yet
I was working on this https://forum.minetest.net/viewtopic.php?f=9&t=22639
Closing this. Let's move there...
